Class {
	#name : #CDTodo,
	#superclass : #Object,
	#category : #'FluidClassDefinition-Visitor'
}

{ #category : #'as yet unclassified' }
CDTodo >> todo1 [

	"pools sohuld be an array of Variable"
]

{ #category : #'as yet unclassified' }
CDTodo >> todo2 [

	"in classDefinitionNodeclassName should be name"
]

{ #category : #'as yet unclassified' }
CDTodo >> todo3 [

	"in ClassDefinition node traitdefnitino is traitComposition "
]
