Class {
	#name : #LegacyClassDefinitionPrinterTest,
	#superclass : #CommonClassDefinitionPrinterTest,
	#category : #'FluidClassDefinition-Printer'
}

{ #category : #running }
LegacyClassDefinitionPrinterTest >> setUp [
	"Hooks that subclasses may override to define the fixture of test."

]

{ #category : #running }
LegacyClassDefinitionPrinterTest >> tearDown [
	"Hooks that subclasses may override to clean the fixture of test."
]
