Class {
	#name : #OldPharoClassDefinitionPrinterTest,
	#superclass : #CommonClassDefinitionPrinterTest,
	#category : #'FluidClassDefinition-Printer-UnderDev'
}

{ #category : #running }
OldPharoClassDefinitionPrinterTest >> setUp [
	"Hooks that subclasses may override to define the fixture of test."

]

{ #category : #running }
OldPharoClassDefinitionPrinterTest >> tearDown [
	"Hooks that subclasses may override to clean the fixture of test."
]
