"
ToTry named: #Tbehavior
	uses: {};
	package: 'plipo'
"
Class {
	#name : #ToTry,
	#superclass : #Object,
	#category : #'FluidClassDefinition-Parser'
}

{ #category : #'instance creation' }
ToTry class >> named: aSymbol package: another [ 

]

{ #category : #'instance creation' }
ToTry class >> named: aSymbol slots: aSlot [ 

]

{ #category : #'instance creation' }
ToTry class >> named: aSymbol uses: anArray [
]

{ #category : #'instance creation' }
ToTry >> named: aSymbol [
]

{ #category : #'instance creation' }
ToTry >> package: aSymbol [
]

{ #category : #'instance creation' }
ToTry >> uses: anArray [
]
